### PR TITLE
v3.8.0

### PR DESCRIPTION
**Pull request by donavanbecker**
### Other Changes
- Update dependencies (`array-flatten`)

### CODE REVIEW

**Comment by donavanbecker** [comment]
I have also changed the GitHub actions to follow what we have setup on other homebridge repos

**Comment by NorthernMan54** [comment]
Can we also update the publish instructions here for the change ? https://github.com/homebridge/documentation/blob/latest/Repositories.md#supporting-packages

**Review by NorthernMan54 — APPROVED** [review]

**Comment by donavanbecker** [comment]
> Quote reply
> Reference

https://github.com/homebridge/documentation/commit/56154e0173805d774ee6e576eb66c892caa6ea30

**Comment by donavanbecker** [comment]
> Can we also update the publish instructions here for the change ? https://github.com/homebridge/documentation/blob/latest/Repositories.md#supporting-packages

https://github.com/homebridge/documentation/commit/56154e0173805d774ee6e576eb66c892caa6ea30

**Pull request merged**
