### PR TITLE
Auto publishing and move default branch to `latest`

### PR DESCRIPTION
**Pull request by NorthernMan54**
**Simple automated publishing for projects**

Automatically publishes beta releases, when a change is pushed to a beta branch
For a latest/production release, workflow must be manually kicked off / started from `Actions --> Build and Publish`.  ( This is by design to prevent accidental production releases.)
Latest release includes a github release

**Release Workflow ( Beta --> Production )**

1 - Determine what the target version will be for the final release and update the package.json version number ( ie `0.5.6`)
2 - Create a new branch including the target release version ie `beta-0.5.6`
3 - Commit the updated package.json to the new beta branch.  This will trigger a npm release with the beta tag, and npm version set to `0.5.6-beta.0`.
4 - As updates are made to the beta branch, npm beta releases will be created.
5 - Once the release is complete, and ready for latest/production release, create a pull request to merge the changes into the `latest` branch.
6 - After reviews are complete, merge the pull request
7 - For the latest/production release, the workflow must be manually kicked off / started from Actions --> Build and Publish
8 - Delete beta branch

### CODE REVIEW

**Comment by NorthernMan54** [comment]
@Supereg - I had already started the effort around this ( 3.6.x ), then saw that you had published 3.7.0 already.  So the GitHub changes are a bit messed up.

The beta publishing is active, and production will be after merging

**Comment by NorthernMan54** [comment]
Publish notes are here

https://github.com/homebridge/documentation/blob/latest/Repositories.md#supporting-packages

Thought about making my simple publishing a shared asset, and will tackle that at some point in the future.

**Review by bauer-andreas — APPROVED** [review]
Thanks for tackling this.

**Comment by NorthernMan54** [comment]
NPM Release published - https://www.npmjs.com/package/bonjour-hap?activeTab=versions
GitHub Release published - https://github.com/homebridge/bonjour/releases

Humm, my script does not include a `v` in the GitHub version tag.  Does it matter ?

**Comment by bauer-andreas** [comment]
> Humm, my script does not include a `v` in the GitHub version tag. Does it matter ?

Makes it inconsistent with all of our other repos. I think there is no one relying on it currently, but could you fix it for the future to add v prefixes again?

**Pull request merged**
